### ISSUE TITLE
Dónde trabajo

### ISSUE THREAD

**Issue by FranLucchini** [farojos/mineConfig#1]
Hola, debo trabajar en Ubuntu o funciona bien en Windows?

**Comment by FranLucchini** [comment]
@farojos

**Comment by farojos** [comment]
funciona correctamente en windows, pero instale git para poder trabajar, yo creo que en la noche voy a hacer un commit grande editando muchas cosas . Te recomiendo ver esta guia para poder editar cosas http://fathertoast.wikia.com/wiki/Mob_Properties .... esa es para editar mobs, y esta para editar furniture mod que añade cosas como lava platos, computador para compras online, etc http://mrcrayfishs-furniture-mod.wikia.com/wiki/Configuration .... hay mas cosas que se pueden configurar, estaba pensando instalar el siguiente mod http://mods.curse.com/mc-mods/minecraft/230368-block-properties#t1:screenshots, con el fin de hacer materiales mas resistentes a la explosiones y asi no explote las contrucciones hechas (nadie quiere que la casa de uno explote y todos sus alrededores tambien por culpa de un solo creeper). El problema es que necesitas mas archivos para poder trabajar . primero necesitas tener instalado minecraft, segundo tener instalado forge,tercero tener todos los mods. El siguiente commit vendra con las config iniciales para poder debuguear
